[package]
name = "mc_server_list_ping"
version = "0.1.1"
authors = ["debilausaure", "irevoire"]
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.40.0", features = ["io-util", "macros", "net", "rt"] }